import { StyleSheet } from "react-native";

const SplashStyle = StyleSheet.create({
  root: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5E6EC",
    flex: 1,
    paddingHorizontal: 20,
    overflow: "hidden",
  },
  blurOverlayTop: {
    position: "absolute",
    top: "-3.46%",
    left: "-13.33%",
    right: "42.56%",
    bottom: "74.23%",
    borderRadius: 9999,
  },
  blurOverlayIcon: {
    position: "absolute",
    left: -8,
    right: -8,
    top: -8,
    bottom: -8,
    borderRadius: 9999,
    zIndex: 0,
  },
  centerContent: {
    alignItems: "center",
    justifyContent: "center",
  },
  logoContainer: {
    width: 160,
    height: 160,
    borderRadius: 65,
    backgroundColor: "#FFFFFF",
    borderWidth: 5,
    borderColor: "#1A1A1A",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 35,
  },
  icon: {
    width: 170,
    height: 170,
    marginBottom: 30,
  },
  mainText: {
    fontSize: 40,
    fontWeight: "900",
    fontFamily: "Semantic",
    color: "#1A1A1A",
    letterSpacing: 2,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 13,
    fontFamily: "Montserrat",
    fontWeight: "500",
    color: "#5A5A5A",
    letterSpacing: 0.8,
    marginBottom: 50,
    textTransform: "uppercase",
  },
  dotsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#1A1A1A",
  },
  version: {
    fontSize: 10,
    color: "#9A8A9A",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  blurOverlayBottom: {
    position: "absolute",
    top: "72.69%",
    left: "22.05%",
    right: "-10.51%",
    bottom: "-13.08%",
    borderRadius: 9999,
  },
});

export default SplashStyle;
